package com.virtualreality.skills;

public enum Skill {

	// Magic
	ALTERATION(), CONJURATION(), DESTRUCTION(), ENCHANTING(), ILLUSION(), 
	RESTORATION(),

	// Combat
	ARCHERY(), BLOCK(), HEAVY_ARMOR(), ONE_HANDED(), SMITHING(), TWO_HANDED(),

	// STEALTH
	ALCHEMY(), LIGHT_ARMOR(), LOCKPICKING(), PICKPOCKET(), SNEAK(), SPEECH();

}
